# Generated by Django 3.1 on 2020-08-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_song_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='media_type',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video')], default='Audio', max_length=5),
        ),
    ]
