# Generated by Django 3.1 on 2020-08-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
