# Generated by Django 3.1 on 2020-08-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_song_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes_count',
        ),
    ]
